### ISSUE TITLE
Implement downloading of audio files

### ISSUE THREAD

**Issue by stepango** [stepango/Archetype#10]
Implement audio files downloading using [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager.html) or custom implementation. With progress tracking and cancel option in the notification.

Add `Download` button to Player screen and Episodes screen.

Hide `Download` button if the file already downloaded.

Replace download button with `Cancel` button for ongoing downloads.
If `Cancel` button pressed - show confirmation dialog

If an error occurred during download replace `Download` button with `Retry` button.

**Comment by nekdenis** [comment]
Implemented here [pull/12](https://github.com/stepango/Archetype/pull/12)
